{% set name = "cdms2" %}
{% set version = "3.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CDAT/cdms/archive/v{{ version }}.tar.gz
  sha256: 106456b6e3c0fb05f65d23c2d259a9d995d54091f75393d2c845f0462ed8dc02
  patches:
    - 0001-Fixes-issue-creating-file-on-OSX-when-compiled-with-clang-and--fstack-protector-string.patch

build:
  number: 6
  skip: True  # [win] 

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - python {{ python }}
    - setuptools
    - cdat_info >=8.2
    - numpy
    - libcdms >=3.1.2
    - libdrs_f >=3.1.2
    - libdrs >=3.1.2
    - cdtime >=3.1.2
    - openblas
    - lazy-object-proxy
    - libnetcdf
  run:
    - python {{ python }}
    - libcf
    - distarray
    - lazy-object-proxy
    - cdtime
    - cdat_info >=8.2
    - {{ pin_compatible('numpy') }}
    - esmf
    - esmpy
    - six
    - libcdms >=3.1.2
    - libdrs_f >=3.1.2
    - libdrs >=3.1.2
    - cdtime >=3.1.2
    - openblas
    - libnetcdf

test:
  commands:
    - export CDAT_ANONYMOUS_LOG=false && python -c "import cdms2"
    - export CDAT_ANONYMOUS_LOG=false && python -c "import cdms2; cdms2.open('test.nc', 'w')"
    - export CDAT_ANONYMOUS_LOG=false && python -c "import cdms2; cdms2.open('test.nc')"
    - export CDAT_ANONYMOUS_LOG=false && python -c "from cdms2 import MV2"

about:
  home: http://github.com/CDAT/cdms
  license: BSD-3-Clause
  license_file: bsd-3-clause.txt
  summary: Community Data Management System
  description: |
    The Community Data Management System is an object-oriented
    data management system, specialized for organizing
    multidimensional, gridded data used in climate
    analysis and simulation.
  doc_url: https://cdms.readthedocs.io/en/latest
  dev_url: http://github.com/CDAT/cdms

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
    - muryanto1
    - downiec
    - jasonb5
    - xylar
