{% set name = "cdms2" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CDAT/cdms/archive/v{{ version }}.tar.gz
  sha256: 8c420b6d8bc673d0398219dd03067ae1a5f2e6a15a967eb6b66773f08ee42d92

build:
  number: 2
  skip: True  # [win] 

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python {{ python }}
    - setuptools
    - cdat_info
    - numpy
    - libcdms >=3.1.2
    - libdrs_f >=3.1.2
    - libdrs >=3.1.2
  run:
    - python {{ python }}
    - libcf
    - distarray
    - cdtime
    - cdat_info
    - {{ pin_compatible('numpy') }}
    - esmf
    - esmpy
    - libcdms >=3.1.2
    - libdrs_f >=3.1.2
    - libdrs >=3.1.2
    - pyopenssl >1.1

test:
  commands:
      - export UVCDAT_ANONYMOUS_LOG=false && python -c "import cdms2"

about:
  home: https://cdms.readthedocs.io/en/latest
  license: '3-Clause BSD'
  license_file: 'bsd-3-clause.txt'
  summary: 'Community Data Management System'
  description: |
    The Community Data Management System is an object-oriented
    data management system, specialized for organizing
    multidimensional, gridded data used in climate
    analysis and simulation.
  dev_url: http://github.com/CDAT/cdms2

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
