{% set name = "cdms2" %}
{% set version = "3.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CDAT/cdms/archive/v{{ version }}.tar.gz
  sha256: 9402bd52e924b3ed05e30f04f300a0b09ad1fd8d288a9365be74f92130a412a6

build:
  number: 7
  skip: True  # [win] 

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - python {{ python }}
    - setuptools
    - cdat_info >=8.2
    - numpy
    - libcdms >=3.1.2
    - libdrs_f >=3.1.2
    - libdrs >=3.1.2
    - openblas
  run:
    - python {{ python }}
    - libcf
    - distarray
    - cdtime
    - cdat_info >=8.2
    - {{ pin_compatible('numpy') }}
    - esmf
    - esmpy
    - libcdms >=3.1.2
    - libdrs_f >=3.1.2
    - libdrs >=3.1.2
    - openblas
    - lazy-object-proxy

test:
  commands:
      - export CDAT_ANONYMOUS_LOG=false && python -c "import cdms2"

about:
  home: https://cdms.readthedocs.io/en/latest
  license: '3-Clause BSD'
  license_file: 'bsd-3-clause.txt'
  summary: 'Community Data Management System'
  description: |
    The Community Data Management System is an object-oriented
    data management system, specialized for organizing
    multidimensional, gridded data used in climate
    analysis and simulation.
  dev_url: http://github.com/CDAT/cdms2

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
    - muryanto1
    - downiec
