{% set name = "cdms2" %}
{% set version = "3.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CDAT/cdms/archive/v{{ version }}.tar.gz
  sha256: 2b4f2ad348581c9831d3dcb785502515da41f0d21be728c8211618871a0caed9
  patches:
    - 0001-fix_version-fix_readthedocs_build_failures.patch
    - 0002-fixes_building_extensions.patch
    - 0003-Removes-modifying-ncmode-with-NC_NETCDF4-flag.patch
    - 0004-fix_add_env_flag_to_disable_mpi4py.patch
    - 0005-env_flag_to_disable_mpi4py_in_regrid2.patch
    - 0006-env_flag_to_disable_mpi4py_in_cdscan.patch
    - 0007-fix_disable_mpi4py_in_dataset.patch
    - 0008-fixes-missing-PY_SSIZE_T_CLEAN-define.patch
    - 0009-changes-int-to-Py_ssize_t-to-allow-PY_SSIZE_T_CLEAN.patch
    - 0010-Adds-LongLong-type-for-CDML.patch
    - 0011-remove-numpy-float-int.patch
    - 0012-remove-libdrs-rename-libgrib2c.patch
    - 0013-esmpy-imports.patch

build:
  number: 23
  skip: True  # [win or py>=311]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - setuptools <60
    - cdat_info
    - numpy
    - libcdms 3
    - cdtime 3
    - openblas
    - lazy-object-proxy
    - libnetcdf
    - libnetcdf * nompi_*
    - jasper
  run:
    - python {{ python }}
    - libcf
    - distarray
    - lazy-object-proxy
    - cdtime 3
    - cdat_info
    - esmf
    - esmpy
    - six
    - libcdms 3
    - cdtime 3
    - openblas
    - libnetcdf
    - jasper

test:
  commands:
    - python -c 'import cdms2'
    - python -c 'import cdms2; cdms2.open("test.nc", "w")'
    - python -c 'import cdms2; cdms2.open("test.nc")'
    - python -c 'import cdms2.MV2'
    - python -c 'import cdms2._bindex'
    - python -c 'import regrid2'
    - python -c 'import regrid2._regrid'
    - python -c 'import regrid2._scrip'
    - python -c 'from regrid2 import ESMFRegrid'
    - cdscan --help

about:
  home: http://github.com/CDAT/cdms
  license: BSD-3-Clause
  license_file: bsd-3-clause.txt
  summary: Community Data Management System
  description: |
    The Community Data Management System is an object-oriented
    data management system, specialized for organizing
    multidimensional, gridded data used in climate
    analysis and simulation.
  doc_url: https://cdms.readthedocs.io/en/latest
  dev_url: http://github.com/CDAT/cdms

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
    - downiec
    - jasonb5
    - xylar
